.\"   Man page for the aqemu project.
.\"
.TH aqemu 1 "June 24, 2009" "v0.7.3"

.SH NAME
aqemu - Qt4 front-end to QEMU and KVM emulators

.SH SYNOPSIS
.B aqemu

.SH DESCRIPTION
\faqemu\fR is a Qt4 graphical interface used to manage QEMU and KVM virtual \
machines.
It has user-friendly interface and allows to set up the majority of QEMU and \
KVM options.

.SH AUTHOR
Andrey Rijov <ANDron142@yandex.ru>
